/**
 * questions.js — Ngân hàng câu hỏi cho Vietnamese Word Quiz
 * Mỗi câu: { id, type, question, hint, answers, correct (0-based), explain }
 */
export const QUESTION_BANK = [
  // ── CHÍNH TẢ ──────────────────────────────────────────────────────────────
  {
    id: 1,
    type: 'spelling',
    question: 'Từ nào viết đúng chính tả?',
    hint: 'Chú ý thanh điệu và phụ âm đầu.',
    answers: ['chăm chỉ', 'chăm chĩ', 'trăm chỉ', 'châm chỉ'],
    correct: 0,
    explain: '"Chăm chỉ" (cần cù, siêng năng) — thanh hỏi ở chữ "chỉ".',
  },
  {
    id: 2,
    type: 'spelling',
    question: 'Từ nào viết đúng chính tả?',
    hint: 'Chú ý phụ âm cuối.',
    answers: ['học sinh', 'học xin', 'hộc sinh', 'học sing'],
    correct: 0,
    explain: '"Học sinh" viết đúng với phụ âm cuối -nh.',
  },
  {
    id: 3,
    type: 'spelling',
    question: 'Từ nào viết sai chính tả?',
    hint: 'Tìm từ viết SAI trong 4 đáp án.',
    answers: ['trường học', 'sân chơi', 'quà tặn', 'bạn bè'],
    correct: 2,
    explain: '"Quà tặn" sai — phải viết là "quà tặng".',
  },
  {
    id: 4,
    type: 'spelling',
    question: 'Điền vần đúng: "con ch___"',
    hint: 'Con vật bơi dưới nước.',
    answers: ['im', 'ém', 'yếm', 'ép'],
    correct: 0,
    explain: '"Con chim" — vần "im".',
  },
  {
    id: 5,
    type: 'spelling',
    question: 'Từ nào viết đúng chính tả?',
    hint: 'Chú ý phụ âm đầu d/gi/r.',
    answers: ['giặt đồ', 'dặt đồ', 'rặt đồ', 'ziặt đồ'],
    correct: 0,
    explain: '"Giặt đồ" viết đúng với phụ âm đầu "gi".',
  },
  // ── NGHĨA TỪ ──────────────────────────────────────────────────────────────
  {
    id: 6,
    type: 'meaning',
    question: '"Lung linh" có nghĩa gần nhất với từ nào?',
    hint: 'Liên quan đến ánh sáng.',
    answers: ['tối tăm', 'lấp lánh', 'ồn ào', 'nhanh nhẹn'],
    correct: 1,
    explain: '"Lung linh" gần nghĩa với "lấp lánh" — ánh sáng phản chiếu đẹp.',
  },
  {
    id: 7,
    type: 'meaning',
    question: '"Chăm chú" có nghĩa là gì?',
    hint: 'Liên quan đến sự tập trung.',
    answers: ['lười biếng', 'mất tập trung', 'chú ý tập trung', 'vội vàng'],
    correct: 2,
    explain: '"Chăm chú" nghĩa là chú ý, tập trung vào việc đang làm.',
  },
  {
    id: 8,
    type: 'meaning',
    question: '"Thân thiện" trái nghĩa với từ nào?',
    hint: 'Tìm từ có nghĩa ngược lại.',
    answers: ['hòa đồng', 'cởi mở', 'xa cách', 'vui vẻ'],
    correct: 2,
    explain: '"Thân thiện" trái nghĩa với "xa cách".',
  },
  {
    id: 9,
    type: 'meaning',
    question: '"Kiên nhẫn" có nghĩa là gì?',
    hint: 'Đức tính trong học tập.',
    answers: ['nóng vội', 'nhẫn nại, không nản', 'rụt rè', 'ồn ào'],
    correct: 1,
    explain: '"Kiên nhẫn" có nghĩa là nhẫn nại, bền bỉ không nản lòng.',
  },
  {
    id: 10,
    type: 'meaning',
    question: 'Từ nào đồng nghĩa với "vui vẻ"?',
    hint: 'Trạng thái tâm lý tích cực.',
    answers: ['buồn bã', 'hớn hở', 'lo lắng', 'tức giận'],
    correct: 1,
    explain: '"Hớn hở" đồng nghĩa với "vui vẻ" — cảm giác phấn khích, vui mừng.',
  },
  // ── ĐIỀN TỪ ───────────────────────────────────────────────────────────────
  {
    id: 11,
    type: 'fill',
    question: 'Điền từ thích hợp: "Bé ___ sách mỗi tối."',
    hint: 'Hành động với sách.',
    answers: ['đọc', 'ngủ', 'chạy', 'vẽ'],
    correct: 0,
    explain: '"Bé đọc sách mỗi tối." — động từ đúng là "đọc".',
  },
  {
    id: 12,
    type: 'fill',
    question: 'Điền từ thích hợp: "Mặt trời ___ mọc ở hướng Đông."',
    hint: 'Thường xuyên xảy ra.',
    answers: ['ít khi', 'đôi khi', 'luôn luôn', 'hiếm khi'],
    correct: 2,
    explain: '"Mặt trời luôn luôn mọc ở hướng Đông." — quy luật tự nhiên.',
  },
  {
    id: 13,
    type: 'fill',
    question: 'Điền từ thích hợp: "Cô giáo ___ học sinh rất nhiệt tình."',
    hint: 'Hành động của giáo viên.',
    answers: ['dạy', 'chơi', 'hát', 'ngủ'],
    correct: 0,
    explain: '"Cô giáo dạy học sinh rất nhiệt tình."',
  },
  {
    id: 14,
    type: 'fill',
    question: 'Điền từ thích hợp: "Bầu trời hôm nay ___ và trong xanh."',
    hint: 'Mô tả thời tiết đẹp.',
    answers: ['tối tăm', 'mưa nhiều', 'nắng đẹp', 'sấm chớp'],
    correct: 2,
    explain: '"Bầu trời hôm nay nắng đẹp và trong xanh."',
  },
  {
    id: 15,
    type: 'fill',
    question: 'Điền từ thích hợp: "Các bạn học sinh ___ đến trường đúng giờ."',
    hint: 'Diễn tả việc di chuyển.',
    answers: ['bay', 'đến', 'nằm', 'khóc'],
    correct: 1,
    explain: '"Các bạn học sinh đến trường đúng giờ."',
  },
  // ── PHÂN LOẠI TỪ ─────────────────────────────────────────────────────────
  {
    id: 16,
    type: 'classify',
    question: 'Từ nào chỉ HOẠT ĐỘNG?',
    hint: 'Tìm động từ — từ diễn tả hành động.',
    answers: ['xinh đẹp', 'bàn ghế', 'nhảy múa', 'màu đỏ'],
    correct: 2,
    explain: '"Nhảy múa" là động từ chỉ hoạt động.',
  },
  {
    id: 17,
    type: 'classify',
    question: 'Từ nào chỉ SỰ VẬT?',
    hint: 'Tìm danh từ — từ chỉ tên sự vật, đồ vật.',
    answers: ['chạy nhanh', 'quyển vở', 'đẹp đẽ', 'vui chơi'],
    correct: 1,
    explain: '"Quyển vở" là danh từ chỉ sự vật.',
  },
  {
    id: 18,
    type: 'classify',
    question: 'Từ nào chỉ ĐẶC ĐIỂM, TÍNH CHẤT?',
    hint: 'Tìm tính từ — từ mô tả đặc điểm.',
    answers: ['học bài', 'con mèo', 'thông minh', 'chạy nhảy'],
    correct: 2,
    explain: '"Thông minh" là tính từ chỉ đặc điểm, tính chất.',
  },
  // ── DẤU CÂU ───────────────────────────────────────────────────────────────
  {
    id: 19,
    type: 'punctuation',
    question: 'Câu nào dùng dấu câu hợp lý nhất?',
    hint: 'Chọn câu rõ ràng, đúng dấu câu.',
    answers: [
      'Hôm nay trời đẹp em đi học.',
      'Hôm nay, trời đẹp em đi học',
      'Hôm nay trời đẹp, em đi học.',
      'Hôm nay trời, đẹp em đi học.',
    ],
    correct: 2,
    explain: '"Hôm nay trời đẹp, em đi học." — dấu phẩy đặt đúng chỗ tách mệnh đề.',
  },
  {
    id: 20,
    type: 'punctuation',
    question: 'Dấu gì dùng để kết thúc câu hỏi?',
    hint: 'Dấu thường gặp sau "Bạn có khỏe không?"',
    answers: ['Dấu chấm .', 'Dấu phẩy ,', 'Dấu chấm hỏi ?', 'Dấu chấm than !'],
    correct: 2,
    explain: 'Câu hỏi kết thúc bằng dấu chấm hỏi (?).',
  },
];

/** Lấy n câu ngẫu nhiên từ ngân hàng */
export function getRandomQuestions(n = 5) {
  const shuffled = [...QUESTION_BANK].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(n, shuffled.length));
}
