export const ANIMAL_MATCH_BANK = [
  {
    id: 1,
    animal: 'Cá',
    emoji: '🐟',
    type: 'habitat',
    prompt: 'Con vật này sống ở đâu?',
    answer: 'Ao hồ',
    options: ['Ao hồ', 'Sa mạc', 'Tổ chim'],
    explanation: 'Cá sống trong nước như ao, hồ, sông hoặc biển.',
    level: 1,
  },
  {
    id: 2,
    animal: 'Khỉ',
    emoji: '🐒',
    type: 'habitat',
    prompt: 'Con vật này sống ở đâu?',
    answer: 'Rừng cây',
    options: ['Rừng cây', 'Băng tuyết', 'Dưới biển'],
    explanation: 'Khỉ thường sống trên cây và trong rừng.',
    level: 1,
  },
  {
    id: 3,
    animal: 'Lạc đà',
    emoji: '🐪',
    type: 'habitat',
    prompt: 'Con vật này sống ở đâu?',
    answer: 'Sa mạc',
    options: ['Sa mạc', 'Ao hồ', 'Ruộng lúa'],
    explanation: 'Lạc đà thích nghi tốt với môi trường sa mạc khô nóng.',
    level: 1,
  },
  {
    id: 4,
    animal: 'Gấu bắc cực',
    emoji: '🐻‍❄️',
    type: 'habitat',
    prompt: 'Con vật này sống ở đâu?',
    answer: 'Băng tuyết',
    options: ['Băng tuyết', 'Rừng nhiệt đới', 'Chuồng gà'],
    explanation: 'Gấu bắc cực sống ở vùng rất lạnh, nhiều băng tuyết.',
    level: 1,
  },
  {
    id: 5,
    animal: 'Ếch',
    emoji: '🐸',
    type: 'habitat',
    prompt: 'Con vật này sống ở đâu?',
    answer: 'Bờ ao ẩm ướt',
    options: ['Bờ ao ẩm ướt', 'Sa mạc cát', 'Núi tuyết'],
    explanation: 'Ếch thích nơi ẩm ướt gần ao, hồ và ruộng.',
    level: 1,
  },
  {
    id: 6,
    animal: 'Chim sẻ',
    emoji: '🐦',
    type: 'habitat',
    prompt: 'Con vật này sống ở đâu?',
    answer: 'Tổ trên cây',
    options: ['Tổ trên cây', 'Dưới nước', 'Trong hang cát'],
    explanation: 'Chim sẻ thường làm tổ trên cây hoặc mái nhà.',
    level: 1,
  },
  {
    id: 7,
    animal: 'Thỏ',
    emoji: '🐰',
    type: 'food',
    prompt: 'Con vật này thích ăn gì?',
    answer: 'Cà rốt',
    options: ['Cà rốt', 'Cá nhỏ', 'Thịt sống'],
    explanation: 'Thỏ là động vật ăn cỏ, thích cà rốt và rau xanh.',
    level: 2,
  },
  {
    id: 8,
    animal: 'Gấu trúc',
    emoji: '🐼',
    type: 'food',
    prompt: 'Con vật này thích ăn gì?',
    answer: 'Tre non',
    options: ['Tre non', 'Kem lạnh', 'Xương cá'],
    explanation: 'Gấu trúc nổi tiếng với thức ăn chính là tre.',
    level: 2,
  },
  {
    id: 9,
    animal: 'Sư tử',
    emoji: '🦁',
    type: 'food',
    prompt: 'Con vật này thích ăn gì?',
    answer: 'Thịt',
    options: ['Thịt', 'Lá cây', 'Hạt gạo'],
    explanation: 'Sư tử là động vật ăn thịt.',
    level: 2,
  },
  {
    id: 10,
    animal: 'Bò',
    emoji: '🐮',
    type: 'food',
    prompt: 'Con vật này thích ăn gì?',
    answer: 'Cỏ',
    options: ['Cỏ', 'Cá', 'Mật ong'],
    explanation: 'Bò ăn cỏ và các loại cây mềm.',
    level: 2,
  },
  {
    id: 11,
    animal: 'Ong',
    emoji: '🐝',
    type: 'food',
    prompt: 'Con vật này tìm gì ở hoa?',
    answer: 'Mật ngọt',
    options: ['Mật ngọt', 'Đá cuội', 'Lá khô'],
    explanation: 'Ong hút mật hoa để làm mật ong.',
    level: 2,
  },
  {
    id: 12,
    animal: 'Gà',
    emoji: '🐔',
    type: 'food',
    prompt: 'Con vật này thường ăn gì?',
    answer: 'Thóc hạt',
    options: ['Thóc hạt', 'Tre non', 'San hô'],
    explanation: 'Gà thường ăn thóc, hạt và côn trùng nhỏ.',
    level: 2,
  },
  {
    id: 13,
    animal: 'Hải cẩu',
    emoji: '🦭',
    type: 'mixed',
    prompt: 'Con vật này hợp nhất với điều gì?',
    answer: 'Biển lạnh và cá',
    options: ['Biển lạnh và cá', 'Sa mạc và xương rồng', 'Tổ cây và hạt thóc'],
    explanation: 'Hải cẩu sống ở vùng biển lạnh và ăn cá.',
    level: 3,
  },
  {
    id: 14,
    animal: 'Voi',
    emoji: '🐘',
    type: 'mixed',
    prompt: 'Con vật này hợp nhất với điều gì?',
    answer: 'Rừng và lá cây',
    options: ['Rừng và lá cây', 'Băng tuyết và cá', 'Nước sâu và rong biển'],
    explanation: 'Voi sống trên cạn, thường ở rừng và ăn lá, cỏ.',
    level: 3,
  },
  {
    id: 15,
    animal: 'Cú mèo',
    emoji: '🦉',
    type: 'mixed',
    prompt: 'Con vật này hợp nhất với điều gì?',
    answer: 'Cây cao và hoạt động ban đêm',
    options: ['Cây cao và hoạt động ban đêm', 'Ao bùn và rong rêu', 'Biển sâu và san hô'],
    explanation: 'Cú mèo thường đậu trên cây và săn mồi vào ban đêm.',
    level: 3,
  },
  {
    id: 16,
    animal: 'Cá heo',
    emoji: '🐬',
    type: 'mixed',
    prompt: 'Con vật này hợp nhất với điều gì?',
    answer: 'Biển và đàn cá nhỏ',
    options: ['Biển và đàn cá nhỏ', 'Núi cao và quả thông', 'Chuồng cỏ và cà rốt'],
    explanation: 'Cá heo sống ở biển và ăn cá nhỏ.',
    level: 3,
  },
  {
    id: 17,
    animal: 'Sóc',
    emoji: '🐿️',
    type: 'mixed',
    prompt: 'Con vật này hợp nhất với điều gì?',
    answer: 'Cây và hạt',
    options: ['Cây và hạt', 'Ao và rong', 'Băng tuyết và cá voi'],
    explanation: 'Sóc thường sống trên cây và thích ăn hạt.',
    level: 3,
  },
  {
    id: 18,
    animal: 'Ngựa',
    emoji: '🐴',
    type: 'mixed',
    prompt: 'Con vật này hợp nhất với điều gì?',
    answer: 'Đồng cỏ và cỏ khô',
    options: ['Đồng cỏ và cỏ khô', 'Biển sâu và tảo', 'Sa mạc và xương rồng'],
    explanation: 'Ngựa sống trên đồng cỏ và ăn cỏ.',
    level: 3,
  },
];

export function getItemsByLevel(level) {
  return ANIMAL_MATCH_BANK.filter((item) => item.level === level);
}

export function getQuestion(level, usedIds = []) {
  const pool = getItemsByLevel(level).filter((item) => !usedIds.includes(item.id));
  const source = pool.length ? pool : getItemsByLevel(level);
  return source[Math.floor(Math.random() * source.length)];
}
